
export const metadata = {
    title: 'Blog Page title',
    description: 'Blog description Generated by create next app',
  };

const layout = ({children}) => {
    return (
        <div>
            {children}
        </div>
    );
};

export default layout;