
export const metadata = {
    title: 'Blog Page title',
    description: 'Blog description Generated by create next app',
  };

const layout = ({children}) => {
    return (
        <div>
            <h2 className='text-2xl font-semibold text-center'>Blog Page</h2>
            {children}
            
        </div>
    );
};

export default layout;